### ISSUE TITLE
GMS2 compatibility?

### ISSUE THREAD

**Issue by worsedoughnut** [puggsoy/GMExtract#1]
Any chance of making this compatible with GMS2-made games without a data.win file?

**Comment by puggsoy** [comment]
Perhaps. I'd like to but I haven't really looked into it yet so I don't know how easy it difficult it'll be. I'm currently working on a version of GMExtract with a GUI and the ability to edit it, which is currently higher priority. However I will look into GMS2 at some point and see what I can do.
