### ISSUE TITLE
Nothing happens

### ISSUE THREAD

**Issue by I-CyberDaun-I** [puggsoy/GMExtract#8]
Greetings. Nothing happens when I try to open the win file from Wicked Games (https://store.steampowered.com/app/1346720/Wicked_Games/). The same problem happened to another user from this thread - https://github.com/puggsoy/GMExtract/issues/2. Please help :)

**Comment by puggsoy** [comment]
Given the release date, this is likely a Game Maker Studio 2 game, which is likely different enough that this won't work. My other project GMS Explorer (https://github.com/puggsoy/GMS-Explorer) is intended to support both versions, but unfortunately it has no release yet and I don't dedicate much time to it anymore.

I will put it in my schedule to make a pre-release build sometime soon and maybe it will suffice.

**Comment by I-CyberDaun-I** [comment]
Great, I'll look forward to it.

пт, 23 июн. 2023 г. в 01:05, Sami Habib ***@***.***>:

**Comment by puggsoy** [comment]
I've made a build for GMS Explorer here: https://github.com/puggsoy/GMS-Explorer/releases

Closing this issue, if it doesn't work then please open an issue on that project.

**Comment by I-CyberDaun-I** [comment]
[image: image.png]
The following problem arises

пн, 3 июл. 2023 г. в 02:35, Sami Habib ***@***.***>:

**Comment by puggsoy** [comment]
It seems the image didn't embed properly. Maybe because you're commenting via email.

Please make a new issue on the GMS Explorer repository with the error image.
