### ISSUE TITLE
max_array_size reached

### ISSUE THREAD

**Issue by disukomusic** [puggsoy/GMExtract#9]
Trying to rip asset's from a studio member's game build, they lost the working files so the build is the only thing that has the assets. This looks super promising but returns this error every time i try to use it:

```
`B:\Documents\Applications\GMExtract_v1.1>GMExtract data.win out -s
GMExtract v1.1 - by puggsoy

Extracting sprites...
Called from ? line 1
Called from Main.hx line 28
Called from Main.hx line 18
Called from Main.hx line 39
Called from easyconsole/Begin.hx line 31
Called from Main.hx line 63
Called from Main.hx line 129
Called from structure/Sprt.hx line 20
Called from structure/Sprite.hx line 28
Uncaught exception - alloc.c(211) : max_array_size reached

B:\Documents\Applications\GMExtract_v1.1>`
```

**Comment by puggsoy** [comment]
Try out the successor to this project, [GMS Explorer](https://github.com/puggsoy/GMS-Explorer).

Although if it's a Game Maker Studio 2 game, chances are it won't work as it only supports GMS 1 games as of now.

**Comment by disukomusic** [comment]
Got it! Tried out GMS Explorer and it seems to have worked, thank you
